# Basic site configuration
base_url = "https://nothing-r.github.io/The_Orcas/"
title = "THE SILENT ORCAS"
description = "Thoughts, tutorials, and insights on technology and cybersecurity"

# Language and timezone
default_language = "en"

# Build settings
compile_sass = true
build_search_index = true
generate_feeds = true

# Markdown configuration
[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

# Extra configuration for your site
[extra]
# Your username/handle that appears in the header
username = "THE SILENT ORCAS"

# Your bio text that appears on the homepage
bio = "Just a curious person who want to know about the digital world."

# Social links
github_url = "https://github.com/NOTHING-R/"  # Optional: add your GitHub URL

# Taxonomy configuration
# Taxonomy configuration
[[taxonomies]]
name = "tags"
paginate_by = 10

[[taxonomies]]
name = "categories"
paginate_by = 10
