* About the system
Ami majhe 2 din er jonno kali te switch korcilam🙂. To 2 din use korar pore ami amr main setup arch+exwm er sob kicu onk miss kortacilam. Asole amr ayta ovbas hoye gece arch ta k use kora ay jonno r ki...arch cara onno kicu use korte gele akhn uncomfortable feel hoi....r ami ay system er upore onk smy dici jinis gula k thik thak korar jonno...So it will always be ARCH THE FAKE SYSTEM.

* Recent Issue
Majhe ami kicu din sob bad dicilam tkhno amr main system hisabe arch e dea cilo kintu ami prai 6 mas notun vabe setup korcilam na. To ami j script ta ready korcilam oita o check kora hoi nai. Kintu ami kicu din age jkhn amr arch setup korte jai amr script ta diye tkhn jhamela hoi amr script ta te kaj kortacilo na. Main issue cilo package gula te. ~i3 dmenu nitrogen~ ay package gula te problem er jonno kno package e install hoccilo na. Pore ami amr script diye ay package gula remove kore dei. Abong er por theke sob package gula thik thak e install hoice. 

* ISSUE WITH NITROGEN
Sob theke kahini marka jinis cilo hocce ~nitrogen~ er issue ta. Karon ami amr wallpaper control korar jonno nitrogen use kortam. Amr sddm er background r betterlockscreen er  background sob kicur script e nitrogen er sathe add cilo ay jonno ami ay jinis gula control korte partecilam na. To er pore ami amr jindegir first wallpaper set kora tool ~feh~ te switch kori r chatgpt k dia amr script ta k thik thak kore nei karon ami code akhn porte pari kintu likhte pari na🙂. Ha to ay vabe e mainly apatato issue gula solve korci akhn sob thik thak kaj kortace.

* REMOVED TOOL AND NEW ADDED TOOLS
Remove kora hoice hocce 3 ta jinis ja age e bolci ~i3 dmenu nitrogen~. R new add korci ~feh~ karon amr wallpaper set korte partaci naaaa😵😵😵. 
