* FAKE SYSTEM DIA KI HOBE? 
** Hudai ato kahini kno? 
Sobar mathai just akta question e asbe duniyai windows 10 & 11, linux er best distro Ubuntu, kali, Debian r ay gular graphical best option gnome, kde abong window manager hisabe most stable i3 r best animation abong feel soho asa hyperland bad diya kno manus hudai ~emacs~ er upor build hoya akta window manager ~exwm~ use korbe jar name dia rakha hoice ~FAKE SYSTEM~. 


To akhn ami amr kotha boli. ami first laptop kini 2023 october a.  To amr cybersecurity er upor onk besi jhok cilo. Ami laptop er age e linux r kali somporke jancilam. To laptop ta kenar pore e vmware dia kali use kora suru kori. Tkhn ami partition file system os somporke kiccu jantam na. Kintu mojar bepar hocce ami windows onk kom use korci. Ami first use kori kali linux. Ami mone hoi laptop kenar 2 mas pore e kali main os hisabe dei. Ami tkhn partam na onno akjon er help nia kaj ta kori. Er pore kali usa kora suru kori kintu tkhn kali onk break hoito akhn er obostha jani na karon onno onk karone use e kora hoi na. So akta stable distro er jonno ghata-ghati suru kori. Pore ak ak kore ubuntu, parrot, linux mint, debian sob use korci kintu sotti bolte kno ta e moner moto cilo na. Ubuntu r parrot hudai frezee hoye jaito. Mint ta re bot bot lagto r debian to raw, linux experience na thakar jonno ami oita use korte pari nai....debian er dos na ami e bot cilam tkhn. To ami 2024 er mid er dike youtube a ~hexdump~ er video dekhi oi hala j ki use korce ami bujhi e nai. To oi system ta dekhe ami pura obak hoye jai j ay jinis to ami age dekhi nai. To ghataghati korte korte bujhlam j o ~emacs~ name a kicu akta use koratce r or oi setup dekhe amio caiclam j amio same vabe amr system use korbo. R ami caccilam akta lightweight setup karon laptop windows dia just calu korle e fan a gan gaoya suru kore dito. R onno distro gulateo onk ta same e bola jai. To hexdump er system ta cilo arch er upore. To ami first kno cybersecurity person k dekhlam j tar main os hisabe arch use kore. Ay jinis ta amk bes motivate kore r o mojar jinis hocce amr jehetu akta lightweight setup dorkar cilo j ta system upor kom pressure dibe to amio same jinis ta setup korar dicision nei. Amr life er sob theke baje othoba sob theke valo decision hobe hocce ayta. Akhn dekha jak  j ki hoi. 

** Ki Ki use hoi FAKE-SYSTEM a? 
Fake system ta ami mainly baniyeci ~emacs~ diye. Amr system a bolte gele emacs e sob kaj kore. File manager, window manager, text editor, majhe majhe code editor, terminal ak kothai bolte gele sob kicu e emacs diya hoye jai ay jonno e ay jinis ta just wow!...Emacs ta k ami onk din dhore e code editor banaite caccilam kintu ayta te onk jhamela pohano lagtace amr ay jonno coding er jonno ~neovim~ ta k choose korci. Jdio ami neovim akhono sikhtaci kintu ja hoice oita apatao enough bola jai. kaj calanor moto. Neovim er ~lazyvim~ ta use kortaci jar sathe amr kicu script add korci. R o kicu pungtami korci. karon jibone bohu mara kheyeci r khaite cai na. Ay jonno ami akta static site create korci ~zola~ static site genaretor dia. R oita k github page dia upload kore rakhci j kkhn ki kortaci na kortaci sob kicu e oita te dia rakhbo, jate kore ami kicu harai felleo mara na kahi. Abr akta personal git repo baniyeci j ta te ami amr recent kaj gula rakhi jate phone er termux diao kaj korte pari on the way. So mainly aida e apatao. Er pore jinis gula khub valo vabe details a likhe present korbo insa'allah.
