* NEOVIM VSCODE
** JJ FOR NORMAL MODE
ami neovim use kori karon keybindings. So amr sob theke usefull keybinding hocce ~jj~ j ta diye ami insert mode theke normal mode a switch kori. To ay same jinis ta vscode a apply korar jonno vs code er ~Command Palatte~ a jeye ~settings.json~ file ta open kore er pore ay snippet ta add korte hobe:
#+begin_example
{
  "vscode-neovim.compositeKeys": {
    "jj": {
      "command": "vscode-neovim.escape"
    }
  }
#+end_example

** NEOVIM LIKE KEYBINDING
Keybinding use korte korte akhn keybinding cara kicu use korte osojjo lage. So ami to kicu jani e na ty chatgpt use kore kicu smy nia amr neovim er keybinding gula motamuti add korar try korci joto dur hoi. To ay keybinding gula rakhte hoi hocce ~keybindings.json~ ay file ta te
#+begin_src json
// Place your key bindings in this file to override the defaults
[
  // ==========================
  // Window Management (SPC-w)
  // ==========================
{
  "key": "space w w",
  "command": "workbench.action.focusNextGroup",
  "when": "neovim.mode != 'insert' && !sideBarVisible"
},
{
  "key": "space w w",
  "command": "workbench.action.focusSideBar",
  "when": "neovim.mode != 'insert' && sideBarVisible && !sideBarFocus"
},
{
  "key": "space w w",
  "command": "workbench.action.focusActiveEditorGroup",
  "when": "neovim.mode != 'insert' && sideBarVisible && sideBarFocus"
},

  {
    "key": "space w v",
    "command": "workbench.action.splitEditorRight",
    "when": "neovim.mode != 'insert'"
  },
  {
    "key": "space w s",
    "command": "workbench.action.splitEditorDown",
    "when": "neovim.mode != 'insert'"
  },
  {
    "key": "space w c",
    "command": "workbench.action.closeActiveEditor",
    "when": "neovim.mode != 'insert'"
  },
{
  "key": "space w h",
  "command": "workbench.action.focusLeftGroup",
  "when": "neovim.mode != 'insert'"
},
{
  "key": "space w l",
  "command": "workbench.action.focusRightGroup",
  "when": "neovim.mode != 'insert'"
},
{
  "key": "space w j",
  "command": "workbench.action.focusBelowGroup",
  "when": "neovim.mode != 'insert'"
},
{
  "key": "space w k",
  "command": "workbench.action.focusAboveGroup",
  "when": "neovim.mode != 'insert'"
}

  // ==========================
  // Buffer Management (SPC-b)
  // ==========================
  {
    "key": "space b p",
    "command": "workbench.action.previousEditor",
    "when": "neovim.mode != 'insert'"
  },
  {
    "key": "space b n",
    "command": "workbench.action.nextEditor",
    "when": "neovim.mode != 'insert'"
  },
  {
    "key": "space b k",
    "command": "workbench.action.closeActiveEditor",
    "when": "neovim.mode != 'insert'"
  },
  {
   "key": "space e",
   "command": "workbench.action.toggleSidebarVisibility",
   "when": "neovim.mode != 'insert'"
  },
  {
  "key": "space b b",
  "command": "multiCommand.toggleLastTwoEditors",
  "when": "neovim.mode != 'insert'"
}
]
#+end_src
 
** BACKGROUND SETUP 
Background set korar jonno ami ay tutorial ta dekhci:
#+BEGIN_EXPORT html
<iframe width="350" height="200"
  src="https://www.youtube.com/embed/tII2WlWaehA"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
  allowfullscreen>
  </iframe>
 #+END_EXPORT

 
So ayta e akhn er jonno apatato notun kicu add korle add kore rakhbo insa'allah.
