* VS CODE A KI KI UPDATE KORLAM
vs code a kicu smossa cilo last update er pore...vs code onk besi powerfull akta eidtor kintu amr moto public er smossa hocce keybinding. Ami keybinding cara system use korte pari na r vim motion cara file eidt korte pari na so amr khub baje akta obvab ayta ay jonno e amr vscode nia naracara kora lagce. R amr onk ta fix hoye gece bola jai 95%. Baki ja ja dorkar jdi hoi kore felbo insa'allah.

** Notun ki ki add kora hoice
Ager config r keybindig gula te smossa cilo hocce terminal toggle kora jaito na neovim ba emacs er moto oita ~ctrl+/~ a add kora hoice. R akta major problem cilo terminal tarpore command pallate kno jaiga te e space key ta kaj korto na oita k fix kora hoice notun kore j ta ~keybindigs.json~ file a add kor hoice.

R akta problem cio copy pasting vim er j smossa ta oita mane just editor er vitore copy paste mane y r p kaj korto oita fix kora hoice ~settings.json~ file a.

So this is the main update of my vscode right now.


* kon kon file a kivabe ki edit kora lagbe 
** setings.json
first a ayta te 2 ta jinis add korte hobe ~jj~ for normal mode r global clipboard for copy paste from every where
#+begin_src json
// Ay line ta hocce jj exit er jonno
{
  "vscode-neovim.compositeKeys": {
    "jj": {
      "command": "vscode-neovim.escape"

    }
  },

  "extensions.experimental.affinity": {
    "asvetliakov.vscode-neovim": 1
  },
  "multiCommand.commands": [
    {
      "command": "multiCommand.toggleLastTwoEditors",
      "sequence": [
        "workbench.action.openPreviousRecentlyUsedEditor"
      ]
    }
  ],
  "glassit.alpha": 2,
  "glassit.force_sway": true,
  "window.menuBarVisibility": "compact",
  "workbench.activityBar.location": "top",
  "window.commandCenter": false,
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "GitHub Dark Default",
  "background.editorBackgrounds": [
    "/home/fake/Downloads/wallpaperflare.com_wallpaper.jpg"
  ],
  "background.enabled": true,
  "background.sidebarBackgrounds": [
    "/home/fake/Downloads/tanjiro-kamado-fire-5120x2880-24474.jpg",
    "/home/fake/FAKE/Fiels/dack.png"
  ],
  "editor.minimap.enabled": false,
  "editor.lineNumbers": "relative",
  "editor.cursorSmoothCaretAnimation": "on",
  "workbench.colorCustomizations": {
    "[Vira*]": {
      "statusBar.debuggingBackground": "#80CBC433",
      "statusBar.debuggingForeground": "#80CBC4",
      "toolbar.activeBackground": "#80CBC426",
      "button.background": "#80CBC4",
      "button.hoverBackground": "#80CBC4cc",
      "extensionButton.separator": "#80CBC433",
      "extensionButton.background": "#80CBC414",
      "extensionButton.foreground": "#80CBC4",
      "extensionButton.hoverBackground": "#80CBC433",
      "extensionButton.prominentForeground": "#80CBC4",
      "extensionButton.prominentBackground": "#80CBC414",
      "extensionButton.prominentHoverBackground": "#80CBC433",
      "activityBarBadge.background": "#80CBC4",
      "activityBar.activeBorder": "#80CBC4",
      "activityBarTop.activeBorder": "#80CBC4",
      "list.inactiveSelectionIconForeground": "#80CBC4",
      "list.activeSelectionForeground": "#80CBC4",
      "list.inactiveSelectionForeground": "#80CBC4",
      "list.highlightForeground": "#80CBC4",
      "sash.hoverBorder": "#80CBC480",
      "list.activeSelectionIconForeground": "#80CBC4",
      "scrollbarSlider.activeBackground": "#80CBC480",
      "editorSuggestWidget.highlightForeground": "#80CBC4",
      "textLink.foreground": "#80CBC4",
      "progressBar.background": "#80CBC4",
      "pickerGroup.foreground": "#80CBC4",
      "tab.activeBorder": "#80CBC4",
      "tab.activeBorderTop": "#80CBC400",
      "tab.unfocusedActiveBorder": "#80CBC4",
      "tab.unfocusedActiveBorderTop": "#80CBC400",
      "tab.activeModifiedBorder": "#80CBC400",
      "notificationLink.foreground": "#80CBC4",
      "editorWidget.resizeBorder": "#80CBC4",
      "editorWidget.border": "#80CBC4",
      "settings.modifiedItemIndicator": "#80CBC4",
      "panelTitle.activeBorder": "#80CBC4",
      "breadcrumb.activeSelectionForeground": "#80CBC4",
      "menu.selectionForeground": "#80CBC4",
      "menubar.selectionForeground": "#80CBC4",
      "editor.findMatchBorder": "#80CBC4",
      "selection.background": "#80CBC440",
      "statusBarItem.remoteBackground": "#80CBC414",
      "statusBarItem.remoteHoverBackground": "#80CBC4",
      "statusBarItem.remoteForeground": "#80CBC4",
      "notebook.inactiveFocusedCellBorder": "#80CBC480",
      "commandCenter.activeBorder": "#80CBC480",
      "chat.slashCommandForeground": "#80CBC4",
      "chat.avatarForeground": "#80CBC4",
      "activityBarBadge.foreground": "#000000",
      "button.foreground": "#000000",
      "statusBarItem.remoteHoverForeground": "#000000"
    }
  },
  "editor.stickyScroll.enabled": false,
  "files.autoSave": "afterDelay",
  "editor.mouseWheelZoom": true,
  "editor.cursorHeight": 4,
  "liveServer.settings.donotShowInfoMsg": true,
  "editor.cursorBlinking": "smooth",
  "liveServer.settings.donotVerifyTags": true,
  "workbench.startupEditor": "none",
  "background.windowBackgrounds": [],

// ay line dui ta dorkar hocce main copy pasting er jonno

  "terminal.integrated.allowChords": false,
  "vscode-neovim.useSystemClipboard": true
}
}
#+end_src

** keybindigs.json ay ta hocce main keybindigs ami ja ja use kori oi jonno 
#+begin_src json
[
  // ==========================
  // Window Management (SPC-w)
  // ==========================
  {
    "key": "space w w",
    "command": "workbench.action.focusNextGroup",
    "when": "editorTextFocus && neovim.mode == 'normal' && !sideBarVisible"
  },
  {
    "key": "space w w",
    "command": "workbench.action.focusSideBar",
    "when": "editorTextFocus && neovim.mode == 'normal' && sideBarVisible && !sideBarFocus"
  },
  {
    "key": "space w w",
    "command": "workbench.action.focusActiveEditorGroup",
    "when": "editorTextFocus && neovim.mode == 'normal' && sideBarVisible && sideBarFocus"
  },
  {
    "key": "space w v",
    "command": "workbench.action.splitEditorRight",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },
  {
    "key": "space w s",
    "command": "workbench.action.splitEditorDown",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },
  {
    "key": "space w c",
    "command": "workbench.action.closeActiveEditor",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },
  {
    "key": "space w h",
    "command": "workbench.action.focusLeftGroup",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },
  {
    "key": "space w l",
    "command": "workbench.action.focusRightGroup",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },
  {
    "key": "space w j",
    "command": "workbench.action.focusBelowGroup",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },
  {
    "key": "space w k",
    "command": "workbench.action.focusAboveGroup",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },

  // ==========================
  // Buffer Management (SPC-b)
  // ==========================
  {
    "key": "space b p",
    "command": "workbench.action.previousEditor",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },
  {
    "key": "space b n",
    "command": "workbench.action.nextEditor",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },
  {
    "key": "space b k",
    "command": "workbench.action.closeActiveEditor",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },
  {
    "key": "space b b",
    "command": "multiCommand.toggleLastTwoEditors",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },

  // ==========================
  // Explorer Toggle (SPC-e)
  // ==========================
  {
    "key": "space e",
    "command": "workbench.action.toggleSidebarVisibility",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },

  // ==========================
  // Terminal Toggle (SPC-t t)
  // ==========================
  {
    "key": "space t t",
    "command": "workbench.action.terminal.toggleTerminal",
    "when": "editorTextFocus && neovim.mode == 'normal'"
  },

  // ==========================
  // Ctrl+/ Terminal Toggle (Global)
  // ==========================
  {
    "key": "ctrl+/",
    "command": "-editor.action.commentLine"
  },
  {
    "key": "ctrl+/",
    "command": "workbench.action.terminal.toggleTerminal"
  }
]
#+end_src
