* A SHORT STORY
** DE
Ami akjon youtuber k follow kori 2024 er last diye [[https://www.youtube.com/@hexdump1337][hexdump1337]]. Uni just akta software e mainly use kore sob kaj er jonno [[https://en.wikipedia.org/wiki/Emacs][emacs]]. From then I got interest into EMACS. And I always want to use my system like [[https://leonardotamiano.xyz/][leonardotamiano]]. Ami 2024 er middle er dik diya emacs niya ghataghati suru kori to amr first target cilo druto jinis gula sikhe kaj suru kore kintu amr sathe sob smy e kno jeno aktu ultapalta hoi to ami tkhn [[https://github.com/doomemacs/doomemacs][DOOM EMACS]] use korte pari nai amr system a kicu error ascilo to tarpore e amr emacs puro scratch theke build kora suru kora lagbe leo er moto akta config paoyar jnno. R emacs er tmn kno valo well documented resources ami youtube abong online a pai na ja dia ami shojei jinis gula sikhte parbo. To ami first a suru kori [[https://www.youtube.com/watch?v=74zOY-vgkyw&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ][system crafters emacs from scratch]] ay playlist ta diye. To onar video ta 4 bocor er moto purano to onk kicu e update hoice emacs er goto 4 bocor a. tobuo joto dur somvob ami oita dia e sekhar try korci abong basic jinis gula sikhci r jkhn ja nia confusion cilo oi ta ChatGpt diya valo vabe bujhe near try korci. To ami jehetu kicui jantam na r updated information khub e kom cilo r amr emacs-lisp er dharonao cilo na kno. to chatgpt er kach theke code niye jkhn emacs a ditam tkhn amon onk bar hoice j amr config abr scratch theke kora lagbe akta code er jonno. To er pore r akta updated youtube playlist pai oita hocce [[https://www.youtube.com/@DistroTube][DistroTube]] Onaro akta emacs from scratch playlist ace [[https://www.youtube.com/watch?v=d1fgypEiQkE&list=PL5--8gKSku15e8lXf7aLICFmAHQVo0KXX&pp=0gcJCV8EOCosWNin][EFS DISTRoTube]]. ayta aktu updated to oita dekhe ami motamuti akta configuretion kore feli amr emacs er jonno. Kintu oi j Leonardotamiano, onar moto configuretion lagbe amr. To oi jinis gular jonno chatgpt abong online a onk ghataghati kora lagce amr jinis gula bojha lagce akta akta kore er pore jeye ami amr emacs ta banaite parci. To ayta akta long process cilo kintu ami happy akhn nijer moto kore nijer emacs ta configuretion korte parate. R motamoti akhn emacs a kno error asle oita bujhte pari abong solve korte pari r akbare notun kicu asle Chatgpt to ace e. So ayvabe e mainly amr system configuretion er suru. Ayta cilo hocce ami amr [[https://en.wikipedia.org/wiki/Desktop_environment][DE]] ta kivbe sajiyeci.

** MAIN OS
Asole ami Windows khub e kom bebohar koreci amr first laptop kena 2023 er November a. To tkhn theke ami kali linux use kortam even phone a o termux use kore linux ta sekhar try kortacilam. To ami jkhn laptop kini tarpore e vmware a kali linux diye amr kali linux e besi use kora hoito karon ami cybersecurity niye besi interested cilam to oi dik theke e kali linux, parrot os ay gular sathe ami poricito hoi. To ami tkhn boot option tarpore kivabe akta os dea jai, kivabe os change kora jai ay sob somporkte amr kno dharone e cilo na. Amr kicu frnd cilo ak ak jon er kach theke ak akta jinis sikhcilam kivabe akta bootable penderive banaite hoi tarpore kivebae os change korte hoi. To amr first laptop r onk sokher jinis ay jonno nije pakami kore kicu korar sahos paccilam na. Tarpore akta frnd er sahajje 1 mas pore first kali linux dei main os hisabe. Tarpore koi ak mas use korar pore dekhlam j kali bar bar e problem kore j kno kicu nia. Hoito puro system crash kore na hoi frezee hoye jai. Akhn alternative khoja suru korlam j ki use kora jai. To er pore Ubuntu tarpore Parrot os use korci kicu din. Kintu amr abr problem ace mon moto na hoile system use kore santi pai na r use o korte pari na. To er pore akdin Sara rat na ghumiye parrot os er look change kore kali linux er moto korcilam. Mane just look change korar jonno sara rat katai dici. Faltu akta kaj cilo oita amr. Parrot use korcilam kicu din valovabe kintu oita te frezee problem cilo mane kicu smy er jonno aka aka e frezee hoye jaito cpu use's 100%  hoye jaito abr aka aka thik hoito to or pore ami abro onno kicu khoja suru kori. R er pasapasi explore korte korte ami bujhlam j nijer system ta asole minimal hoye ucit abong sob kicu nijer moto kore sajano ucit kintu aytar jonno sob theke valo 2 ta option. 

1. [[https://www.debian.org/][Debian]] 
2. [[https://archlinux.org/][ARCH LINUX]]

akhn arch to advance userder jonno ami to kicui pari na linux er tmn. Just gpt er kach theke r online tutorial theke dekhe dekhe sob sikci. Bolte gele just copy paste korci sob kicu. To majhe pakami kore 22GB diye blackarch install korcilam vmware a. To blackarch maybe jkno akta Window Manager use kortacilo. R amr tkhn Window Manager somporkte kno idea e cilo na oi jonno ami oi vabe jinis gula bujhi nai r useo kora hoi nai kno smy. Er pore ami mainly Ubuntu use kora suru kori. To er pore ase akta turning point amr life er. Ami first leonardotamiano er youtube ta dekhi to onar video and workflow dekhe ami to purai obak j ayta ki. kno mouse nai kiccu na kmne kmne koi koi cole jacce kivabe ki kortace uni. ayta ki use kortace. To pore aste aste jante parlam j uni arch linux abong exwm use kortace. EXWM? ayta abr ki jinis. To ami ghataghati suru korlam j jinis ta ki to er pore amr samne first [[https://wiki.archlinux.org/title/Window_manager][Window Manager]] er concept ta aslo. Amr first window manager cilo [[https://i3wm.org/][i3wm]]. Ami aste aste motamuti i3 sekha start korcilam kivabe window manager kaj kore kivebe ki hoi sob kicu kivabe config file edit korte hoi file kothai thake config file ki. Ay sob kicu motamuti sekha suru kori abong aste aste jinis gula nia kaj korte thaki. 
Er pore ami window Manager sekhar kaj a laiga gelam. J aybar ayta sekha lagbe onar moto configuretion banano lagbe. To prothome ami arch ta install kora sekha suru kori j kivabe kore jehteu amr ay sob dik a kno knowledge e nai so ami asole just tutorial na bujhe e follow kortam even akhono ami ay sob somporkte sikhteci. Ami just akjon beginner. Sob kicu explore kortaci abong sekhar try kortaci. To ami first a jkhn install korte jai tkhn ami kiccu bujhi nai just ay video ta follow korci: 
#+BEGIN_EXPORT html
<iframe width="560" height="315"
  src="https://www.youtube.com/embed/AYxaNjbC1wg"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
  allowfullscreen>
  </iframe>
#+END_EXPORT 

Even akhono ami ay same vabe e arch install kori manually pari na. Tobe issa ace Insa'allah aste aste sekhar jate sob jinis gula bujhte pari j kivabe ki kaj kore. To Akhn as a main os ami [[https://archlinux.org/][Arch Linux]] abong [[https://wiki.archlinux.org/title/Desktop_environment][DE]] abong [[https://wiki.archlinux.org/title/Window_manager][WM]] hisabe Emacs x Window Manager mane [[https://github.com/emacs-exwm/exwm][EXMW]] use korci.

** Conclusion
So ayta cilo akta short introduction j ami ki ki use kortaci mainly r kivabe full system setup kora jai oibepare poroborti te kotha hobe insa'allah.
